project_id = "snmtupjzgpoaezicrfck"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.activate-free-trial]
verify_jwt = false

[functions.check-free-trial]
verify_jwt = false

[functions.send-trial-reminders]
verify_jwt = false
